
export const LOG_USER_IN = 'LOG_USER_IN';
export const LOG_USER_OUT = 'LOG_USER_OUT';
export const REGISTER_USER = 'REGISTER_USER'
export const GET_USER_INFORMATION = 'GET_USER_INFORMATION'
export const UNATHORIZED = 'UNATHORIZED'
export const GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES'


export const GEL_ALL_USERS ='GEL_ALL_USERS'
export const GET_ALL_TRANSACTIONS ='GET_ALL_TRANSACTIONS'
export const GET_ALL_PRODUCTS ='GET_ALL_PRODUCTS'